version: '3.8'

services:
  mongodb:
    image: mongo:5.0
    container_name: mongodb
    restart: always
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: ogwplus

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    ports:
      - "3000:3000"
    environment:
      MONGODB_URI: mongodb://mongodb:27017/ogwplus
      JWT_SECRET: your_jwt_secret_here
      JWT_EXPIRES_IN: 90d
    depends_on:
      - mongodb

  admin:
    build:
      context: .
      dockerfile: Dockerfile.admin
    container_name: admin
    restart: always
    ports:
      - "8080:8080"
    environment:
      VUE_APP_API_URL: http://backend:3000
    depends_on:
      - backend

  bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    container_name: bot
    restart: always
    environment:
      TELEGRAM_BOT_TOKEN: your_bot_token_here
      API_URL: http://backend:3000
    depends_on:
      - backend

volumes:
  mongodb_data: